### ISSUE TITLE
Help HTTP over TCP tunnel

### ISSUE THREAD

**Issue by ingnelson** [matansh/golang-tcp-proxy#1]
Hello @matansh 

i am from America, it is possible with your knowledge create a HTTP over TCP tunnel to bypass my isp provider on GO ? 
because HTTPS or TLS or SSL is blocks by my ISP provider.

i think it is difficul for me .
i did all the test to check the isp restrictions.

my telegram is : @Trader_Nelson

i will wait your response.

**Comment by matansh** [comment]
Hey @ingnelson 
Unfortunately, as far as i know, there is no option to bypass your ISP. 
The ISP is essentially your doorway to the internet and in most cases the cables running from your house will go directly to one of the ISP's relay boxes / servers.

About HTTPS being blocked, i find it hard to believe that this is indeed the case, most (if not all) web sites today are served over HTTPS (including this very site - https://github.com) 

Sorry i couldn't help and good luck :)
